/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Cliente.Cliente;
import Cliente.Jugador;
import Componentes.Armas;
import Componentes.Conector;
import Componentes.Mina;
import Componentes.TemploBruja;
import Mar.Isla;
import Modelos.Mensaje;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import java.io.IOException;
import GUI.Matriz;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author hdani
 */
public class Play extends javax.swing.JFrame {
    public Matriz[][] labels;
    
    public Matriz[][] labelsEnemigos;
    Cliente cliente;
    TiendaComponentes tienda;

    /**
     * Creates new form Play
     */
    public Play() {
        initComponents();
        this.setLocationRelativeTo(null);
        labels = new Matriz [20][20];
        labelsEnemigos = new Matriz [20][20];        
        generarLabels();
        generarLabelsPlayer();
        cliente = new Cliente(this);
    }
    
    public void write(String text){
        this.jTextArea1.append(text + "\n");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panelCuadricula = new javax.swing.JPanel();
        panelCuadriculaPlayer = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        tituloPanel2 = new javax.swing.JPanel();
        tituloLabel2 = new javax.swing.JLabel();
        player2Panel = new javax.swing.JPanel();
        player3Panel = new javax.swing.JPanel();
        player4Panel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        textoPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_bitacora = new javax.swing.JTextArea();
        comandoInput = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        historialPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        label_acero = new javax.swing.JLabel();
        label_dinero = new javax.swing.JLabel();
        button_comprar_componentes = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel_canion_barba_roja = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_multiple = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel_canion = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel_bomba = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        colorFuentePanel = new javax.swing.JPanel();
        colorMercadoPanel = new javax.swing.JPanel();
        colorConectorPanel = new javax.swing.JPanel();
        colorMinaPanel = new javax.swing.JPanel();
        colorTemploPanel = new javax.swing.JPanel();
        colorArmeriaPanel = new javax.swing.JPanel();
        armeriaLabel = new javax.swing.JLabel();
        fuenteLabel = new javax.swing.JLabel();
        mercadoLabel = new javax.swing.JLabel();
        conectorLabel = new javax.swing.JLabel();
        minaLabel = new javax.swing.JLabel();
        temploLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        islaCombo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jButton_player2 = new javax.swing.JButton();
        jButton_player1 = new javax.swing.JButton();
        jButton_player3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setBackground(new java.awt.Color(0, 0, 102));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCuadricula.setBackground(new java.awt.Color(0, 0, 102));
        panelCuadricula.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout panelCuadriculaLayout = new javax.swing.GroupLayout(panelCuadricula);
        panelCuadricula.setLayout(panelCuadriculaLayout);
        panelCuadriculaLayout.setHorizontalGroup(
            panelCuadriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCuadriculaLayout.setVerticalGroup(
            panelCuadriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg.add(panelCuadricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 61, -1, -1));

        panelCuadriculaPlayer.setBackground(new java.awt.Color(0, 0, 102));
        panelCuadriculaPlayer.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout panelCuadriculaPlayerLayout = new javax.swing.GroupLayout(panelCuadriculaPlayer);
        panelCuadriculaPlayer.setLayout(panelCuadriculaPlayerLayout);
        panelCuadriculaPlayerLayout.setHorizontalGroup(
            panelCuadriculaPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCuadriculaPlayerLayout.setVerticalGroup(
            panelCuadriculaPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg.add(panelCuadriculaPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        tituloPanel.setBackground(new java.awt.Color(102, 102, 102));

        tituloLabel.setFont(new java.awt.Font("Engravers MT", 3, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("MY SEA");
        tituloLabel.setToolTipText("");

        javax.swing.GroupLayout tituloPanelLayout = new javax.swing.GroupLayout(tituloPanel);
        tituloPanel.setLayout(tituloPanelLayout);
        tituloPanelLayout.setHorizontalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tituloPanelLayout.setVerticalGroup(
            tituloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(tituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 500, 30));

        tituloPanel2.setBackground(new java.awt.Color(102, 102, 102));
        tituloPanel2.setPreferredSize(new java.awt.Dimension(127, 37));

        tituloLabel2.setFont(new java.awt.Font("Engravers MT", 3, 24)); // NOI18N
        tituloLabel2.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel2.setText("Enemy");

        javax.swing.GroupLayout tituloPanel2Layout = new javax.swing.GroupLayout(tituloPanel2);
        tituloPanel2.setLayout(tituloPanel2Layout);
        tituloPanel2Layout.setHorizontalGroup(
            tituloPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloPanel2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(tituloLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tituloPanel2Layout.setVerticalGroup(
            tituloPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(tituloPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 500, 30));

        javax.swing.GroupLayout player2PanelLayout = new javax.swing.GroupLayout(player2Panel);
        player2Panel.setLayout(player2PanelLayout);
        player2PanelLayout.setHorizontalGroup(
            player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        player2PanelLayout.setVerticalGroup(
            player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg.add(player2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 80, -1, 70));

        javax.swing.GroupLayout player3PanelLayout = new javax.swing.GroupLayout(player3Panel);
        player3Panel.setLayout(player3PanelLayout);
        player3PanelLayout.setHorizontalGroup(
            player3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        player3PanelLayout.setVerticalGroup(
            player3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg.add(player3Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 190, -1, -1));

        javax.swing.GroupLayout player4PanelLayout = new javax.swing.GroupLayout(player4Panel);
        player4Panel.setLayout(player4PanelLayout);
        player4PanelLayout.setHorizontalGroup(
            player4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        player4PanelLayout.setVerticalGroup(
            player4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg.add(player4Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 300, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 410, -1, -1));

        textoPanel.setBackground(new java.awt.Color(0, 102, 204));
        textoPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        textoPanel.setForeground(new java.awt.Color(204, 204, 204));

        jTextArea_bitacora.setEditable(false);
        jTextArea_bitacora.setColumns(20);
        jTextArea_bitacora.setRows(5);
        jScrollPane2.setViewportView(jTextArea_bitacora);

        javax.swing.GroupLayout textoPanelLayout = new javax.swing.GroupLayout(textoPanel);
        textoPanel.setLayout(textoPanelLayout);
        textoPanelLayout.setHorizontalGroup(
            textoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
        textoPanelLayout.setVerticalGroup(
            textoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );

        bg.add(textoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 500, 170));

        comandoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comandoInputActionPerformed(evt);
            }
        });
        bg.add(comandoInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 380, 30));

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 710, 120, 30));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout historialPanelLayout = new javax.swing.GroupLayout(historialPanel);
        historialPanel.setLayout(historialPanelLayout);
        historialPanelLayout.setHorizontalGroup(
            historialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historialPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        historialPanelLayout.setVerticalGroup(
            historialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historialPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(historialPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 500, 110));

        label_acero.setFont(new java.awt.Font("Engravers MT", 2, 14)); // NOI18N
        label_acero.setForeground(new java.awt.Color(255, 255, 255));
        label_acero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_acero.setText("jLabel1");
        label_acero.setToolTipText("");
        label_acero.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label_acero.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        label_acero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_aceroMouseClicked(evt);
            }
        });
        bg.add(label_acero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 60, 140, 30));

        label_dinero.setFont(new java.awt.Font("Engravers MT", 2, 14)); // NOI18N
        label_dinero.setForeground(new java.awt.Color(255, 255, 255));
        label_dinero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_dinero.setText("jLabel1");
        label_dinero.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bg.add(label_dinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 140, 30));

        button_comprar_componentes.setText("Comprar componentes");
        button_comprar_componentes.setEnabled(false);
        button_comprar_componentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_comprar_componentesActionPerformed(evt);
            }
        });
        bg.add(button_comprar_componentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 390, 160, 40));

        jLabel_canion_barba_roja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_canion_barba_roja.setText("jLabel1");
        jLabel_canion_barba_roja.setEnabled(false);
        jLabel_canion_barba_roja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_canion_barba_rojaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_canion_barba_roja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_canion_barba_roja, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 350, 160, 30));

        jLabel_multiple.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_multiple.setText("jLabel1");
        jLabel_multiple.setEnabled(false);
        jLabel_multiple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_multipleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_multiple, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_multiple, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 270, 160, 30));

        jLabel_canion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_canion.setText("jLabel1");
        jLabel_canion.setEnabled(false);
        jLabel_canion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_canionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_canion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel_canion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 230, 160, 30));

        jLabel_bomba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_bomba.setText("jLabel1");
        jLabel_bomba.setEnabled(false);
        jLabel_bomba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_bombaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_bomba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_bomba, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 310, 160, 30));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        bg.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 440, -1, -1));

        jButton3.setText("Comodin");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        bg.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 440, -1, -1));

        colorFuentePanel.setBackground(new java.awt.Color(204, 0, 51));
        colorFuentePanel.setToolTipText("");

        javax.swing.GroupLayout colorFuentePanelLayout = new javax.swing.GroupLayout(colorFuentePanel);
        colorFuentePanel.setLayout(colorFuentePanelLayout);
        colorFuentePanelLayout.setHorizontalGroup(
            colorFuentePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        colorFuentePanelLayout.setVerticalGroup(
            colorFuentePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(colorFuentePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 580, 30, 30));

        colorMercadoPanel.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout colorMercadoPanelLayout = new javax.swing.GroupLayout(colorMercadoPanel);
        colorMercadoPanel.setLayout(colorMercadoPanelLayout);
        colorMercadoPanelLayout.setHorizontalGroup(
            colorMercadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        colorMercadoPanelLayout.setVerticalGroup(
            colorMercadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(colorMercadoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 610, -1, -1));

        javax.swing.GroupLayout colorConectorPanelLayout = new javax.swing.GroupLayout(colorConectorPanel);
        colorConectorPanel.setLayout(colorConectorPanelLayout);
        colorConectorPanelLayout.setHorizontalGroup(
            colorConectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        colorConectorPanelLayout.setVerticalGroup(
            colorConectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(colorConectorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 640, -1, -1));

        colorMinaPanel.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout colorMinaPanelLayout = new javax.swing.GroupLayout(colorMinaPanel);
        colorMinaPanel.setLayout(colorMinaPanelLayout);
        colorMinaPanelLayout.setHorizontalGroup(
            colorMinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        colorMinaPanelLayout.setVerticalGroup(
            colorMinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(colorMinaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 670, -1, -1));

        colorTemploPanel.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout colorTemploPanelLayout = new javax.swing.GroupLayout(colorTemploPanel);
        colorTemploPanel.setLayout(colorTemploPanelLayout);
        colorTemploPanelLayout.setHorizontalGroup(
            colorTemploPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        colorTemploPanelLayout.setVerticalGroup(
            colorTemploPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(colorTemploPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 700, -1, -1));

        colorArmeriaPanel.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout colorArmeriaPanelLayout = new javax.swing.GroupLayout(colorArmeriaPanel);
        colorArmeriaPanel.setLayout(colorArmeriaPanelLayout);
        colorArmeriaPanelLayout.setHorizontalGroup(
            colorArmeriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        colorArmeriaPanelLayout.setVerticalGroup(
            colorArmeriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(colorArmeriaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 730, -1, -1));

        armeriaLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        armeriaLabel.setForeground(new java.awt.Color(255, 255, 255));
        armeriaLabel.setText("<= Armeria");
        bg.add(armeriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 730, 100, 30));

        fuenteLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        fuenteLabel.setForeground(new java.awt.Color(255, 255, 255));
        fuenteLabel.setText("<= Fuente");
        bg.add(fuenteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 580, 100, 30));

        mercadoLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        mercadoLabel.setForeground(new java.awt.Color(255, 255, 255));
        mercadoLabel.setText("<= Mercado");
        bg.add(mercadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 610, 110, 30));

        conectorLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        conectorLabel.setForeground(new java.awt.Color(255, 255, 255));
        conectorLabel.setText("<= Conector");
        bg.add(conectorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 640, 110, 30));

        minaLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        minaLabel.setForeground(new java.awt.Color(255, 255, 255));
        minaLabel.setText("<= Mina");
        bg.add(minaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 670, 100, 30));

        temploLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        temploLabel.setForeground(new java.awt.Color(255, 255, 255));
        temploLabel.setText("<=Templo");
        bg.add(temploLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 700, 100, 30));

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 520, 60, 40));

        islaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuente", "Mercado", "Conector" }));
        islaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                islaComboActionPerformed(evt);
            }
        });
        bg.add(islaCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 480, -1, -1));

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 520, -1, -1));

        jButton_player2.setText("Player 1");
        jButton_player2.setEnabled(false);
        jButton_player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_player2ActionPerformed(evt);
            }
        });
        bg.add(jButton_player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 130, 150, 30));

        jButton_player1.setText("Player 1");
        jButton_player1.setEnabled(false);
        jButton_player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_player1ActionPerformed(evt);
            }
        });
        bg.add(jButton_player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 100, 150, 30));

        jButton_player3.setText("Player 1");
        jButton_player3.setEnabled(false);
        jButton_player3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_player3ActionPerformed(evt);
            }
        });
        bg.add(jButton_player3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 160, 150, 30));

        jButton4.setText("Iniciar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        bg.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comandoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comandoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comandoInputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            if(comandoInput.getText().toUpperCase().equals("COMODIN")){
                System.out.println(cliente.jugador.comodin);
                if(cliente.jugador.comodin != 0){
                    switch(cliente.jugador.comodin){
                        case 1->{
                            cliente.salida.writeObject(new Mensaje(cliente.nombre, comandoInput.getText()+"-ESCUDO"));
                            break;
                        }
                        case 2->{
                            cliente.salida.writeObject(new Mensaje(cliente.nombre, comandoInput.getText()+"-KRAKEN"));
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "No tienes comodines", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                if(comandoInput.getText().split("-")[0].equals("VENDER")){
                    if(this.cliente.jugador.tiene_mercado)
                        cliente.salida.writeObject(new Mensaje(cliente.nombre, comandoInput.getText()));
                    else
                        JOptionPane.showMessageDialog(null, "No tienes un mercado", "Aviso", JOptionPane.WARNING_MESSAGE);
                }else
                    cliente.salida.writeObject(new Mensaje(cliente.nombre, comandoInput.getText()));
            }
            
        } catch (IOException ex) {
            //Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        Graphics g = panelCuadricula.getGraphics();
        g.drawLine(25,25,250,250);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void islaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_islaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_islaComboActionPerformed

    private void button_comprar_componentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_comprar_componentesActionPerformed
        tienda = new TiendaComponentes();
        tienda.setVisible(true);
        tienda.setJugador(this.cliente.jugador);
        tienda.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_button_comprar_componentesActionPerformed

    private void label_aceroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_aceroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_aceroMouseClicked

    private void jLabel_canionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_canionMouseClicked
        if(this.jLabel_canion.isEnabled()){
            if(this.cliente.jugador.canion > 0)
                this.cliente.jugador.cargar_arma("CANION");        
            else
                JOptionPane.showMessageDialog(null, "No tienes caniones en tu inventario", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jLabel_canionMouseClicked

    private void jLabel_multipleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_multipleMouseClicked
        if(this.jLabel_multiple.isEnabled()){
            if(this.cliente.jugador.canion_multiple > 0)
                this.cliente.jugador.cargar_arma("CANION MULTIPLE");
            else
                JOptionPane.showMessageDialog(null, "No tienes caniones multiples en tu inventario", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jLabel_multipleMouseClicked

    private void jLabel_bombaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_bombaMouseClicked
        if(this.jLabel_bomba.isEnabled()){
            if(this.cliente.jugador.bomba > 0)
                this.cliente.jugador.cargar_arma("BOMBA");
            else
                JOptionPane.showMessageDialog(null, "No tienes bombas en tu inventario", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jLabel_bombaMouseClicked

    private void jLabel_canion_barba_rojaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_canion_barba_rojaMouseClicked
        if(this.jLabel_canion_barba_roja.isEnabled()){
            if(this.cliente.jugador.canion_barba_roja > 0)
                this.cliente.jugador.cargar_arma("CANION BARBA ROJA");
            else
                JOptionPane.showMessageDialog(null, "No tienes caniones barba roja en tu inventario", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jLabel_canion_barba_rojaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if(cliente.jugador.comodin != 0){
            switch(cliente.jugador.comodin){
                case 1->{
                    Random random = new Random();
                    this.cliente.jugador.escudos = random.nextInt(4)+2;
                    cliente.jugador.comodin = 0;
                    this.cliente.jugador.avisarEscudoActivo();
                    break;
                }
                case 2->{
                    this.cliente.jugador.cargar_arma("KRAKEN");
                    cliente.jugador.comodin = 1;
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "No tienes comodines", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Mina mina = new Mina(this.cliente.jugador,2,100);
        Isla isla1 = new Isla(mina);
        isla1.setX(1);
        isla1.setY(1);
        Mina mina1 = new Mina(this.cliente.jugador,2,100);
        Isla isla2 = new Isla(mina1);
        isla2.setX(2);
        isla2.setY(2);
        Isla isla3 = new Isla(new Conector(isla1,isla2));
        isla3.setX(3);
        isla3.setY(3);        
        this.cliente.jugador.grafo.agregarArista( isla1,isla2 );

        /*/Mina(Jugador jugador,int segundos_en_producir,int kgs_acero_que_produce) {
        Isla isla1 = new Isla(new Mina(this.cliente.jugador,2,100));
        isla1.setX(1);
        isla1.setY(1);
        Isla isla2 = new Isla(new Mina(this.cliente.jugador,2,100));
        isla2.setX(19);
        isla2.setY(19);
          //  this.cliente.jugador.grafo.agregarIsla(isla1);
           // this.cliente.jugador.grafo.agregarIsla(isla2);*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel3jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3jPanel1MouseClicked
        Graphics g = panelCuadricula.getGraphics();
        
        g.drawLine(0,0,250,250);
    }//GEN-LAST:event_jPanel3jPanel1MouseClicked

    private void jButton_player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_player2ActionPerformed
        try {
            this.cliente.salida.writeObject(new Mensaje(this.cliente.nombre,true,this.jButton_player2.getText()));
        } catch (IOException ex) {
            Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_player2ActionPerformed

    private void jButton_player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_player1ActionPerformed
        try {
            this.cliente.salida.writeObject(new Mensaje(this.cliente.nombre,true,this.jButton_player1.getText()));
        } catch (IOException ex) {
            Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_player1ActionPerformed

    private void jButton_player3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_player3ActionPerformed
        try {
            this.cliente.salida.writeObject(new Mensaje(this.cliente.nombre,true,this.jButton_player3.getText()));
        } catch (IOException ex) {
            Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_player3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.jButton4.setVisible(false);
        this.remove(this.jButton4);
        try {
            this.cliente.salida.writeObject(new Mensaje(true));
        } catch (IOException ex) {
            Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }
    
    private void generarLabels(){//yo 
        Border blackline = BorderFactory.createLineBorder(Color.black);
        int x = 0;
        int y = 0;
        for (int i = 0; i < 20; i++){
            y = 0;
            for(int j = 0; j < 20; j++){
                // Label de dígitos
                JLabel label = new JLabel("", SwingConstants.CENTER);     
                label.setFont(new Font("Verdana", Font.PLAIN, 18));
                label.setBounds(x, y, 25, 25);
                label.setOpaque(true);
                label.setBackground(Color.blue);
                label.setBorder(blackline);
                label.setCursor(new Cursor(Cursor.HAND_CURSOR));
                label.addMouseListener(new MouseAdapter(){  
                    public void mouseClicked(MouseEvent e){
                        String selecteditem = islaCombo.getSelectedItem().toString();
                        int sisX = label.getLocation().x;
                        int sisY = label.getLocation().y;
                        switch(selecteditem){
                            case "Fuente":
                                labels[sisX/25][sisY/25].cambieColor(selecteditem);
                                labels[sisX/25 + 1][sisY/25].cambieColor(selecteditem);
                                labels[sisX/25][sisY/25 - 1].cambieColor(selecteditem);
                                labels[sisX/25 + 1][sisY/25 - 1].cambieColor(selecteditem);
                                break;
                            case "Conector":
                                labels[sisX/25][sisY/25].cambieColor(selecteditem);
                                break;
                            case "Mercado":
                                String pos = posicionIsla();
                                if("1x2".equals(pos)){
                                    labels[sisX/25][sisY/25].cambieColor(selecteditem);
                                    labels[sisX/25][sisY/25 + 1].cambieColor(selecteditem);
                                }
                                if("2x1".equals(pos)){
                                    labels[sisX/25][sisY/25].cambieColor(selecteditem);
                                    labels[sisX/25 + 1][sisY/25].cambieColor(selecteditem);
                                }
                                break;
                        }
                    }
                });
                panelCuadricula.add(label);
                labels[i][j] = new Matriz(label);
                y += 25;
            }
            x += 25;
        }    
    }

     private void generarLabelsPlayer(){//Enemigo
         
        Border blackline = BorderFactory.createLineBorder(Color.black);
        int x = 0;
        int y = 0;
        for (int i = 0; i < 20; i++){
            y = 0;
            for(int j = 0; j < 20; j++){
                // Label de dígitos
                JLabel label = new JLabel("", SwingConstants.CENTER);     
                label.setFont(new Font("Verdana", Font.PLAIN, 18));
                label.setBounds(x, y, 25, 25);
                label.setOpaque(true);
                label.setBackground(Color.blue);
                label.setBorder(blackline);
                label.setCursor(new Cursor(Cursor.HAND_CURSOR));
                label.addMouseListener(new MouseAdapter(){  
                    public void mouseClicked(MouseEvent e){
                        if(cliente.jugador.arma_cargada.getX() != -1){
                            String selecteditem = islaCombo.getSelectedItem().toString();
                            int sisX = label.getLocation().x;
                            int sisY = label.getLocation().y;
                            try {
                                if(cliente.jugador.arma_cargada.getName().equals("Kraken")){
                                    cliente.jugador.arma_cargada.setXY(sisX/25, sisY/25);
                                    cliente.salida.writeObject(new Mensaje(cliente.nombre,cliente.jugador.target,cliente.jugador.arma_cargada.getName(),cliente.jugador.arma_cargada.getX(),cliente.jugador.arma_cargada.getY()));
                                }
                                if(cliente.jugador.arma_cargada.getName().equals("Bomba")){
                                    cliente.jugador.arma_cargada.setXY(posicion_disparo(sisX/25,sisY/25));
                                    label.setText("X");
                                    labelsEnemigos[cliente.jugador.arma_cargada.getXY()[2]][cliente.jugador.arma_cargada.getXY()[3]].setText("X");
                                    cliente.salida.writeObject(new Mensaje(cliente.nombre,cliente.jugador.target,cliente.jugador.arma_cargada.getName(),cliente.jugador.arma_cargada.getXY()));                                
                                }else{
                                    cliente.jugador.arma_cargada.setXY(sisX/25, sisY/25);
                                    label.setText("X");    
                                    cliente.salida.writeObject(new Mensaje(cliente.nombre,cliente.jugador.target,cliente.jugador.arma_cargada.getName(),cliente.jugador.arma_cargada.getX(),cliente.jugador.arma_cargada.getY()));
                                }
                            } catch (IOException ex) {
                                Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            cliente.jugador.disparar_arma_cargada();
                        }else{
                            JOptionPane.showMessageDialog(null, "No tienes ningun arma cargada", "Aviso", JOptionPane.WARNING_MESSAGE);
                        }
                    }
                });
                panelCuadriculaPlayer.add(label);
                labelsEnemigos[i][j] = new Matriz(label);
                y += 25;
            }
            x += 25;
        }    
    }
     
    String posicionIsla(){
        String[] options = { "1x2", "2x1"};
        while(true){
            int selectedOption = JOptionPane.showOptionDialog(
                null,
                "Seleccione la orientacion del mercado",
                "Custom Options",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                null,
                options,
                options[0]
            );

            if (selectedOption != JOptionPane.CLOSED_OPTION) {
                return options[selectedOption];
            }
        }
    }
    

    
    int[] posicion_disparo(int x, int y){
        Random random = new Random();
        int randomPos = random.nextInt(4);
        switch(randomPos){
            case 0 ->{
                int[] positions = {x,y,x,y+1};
                return positions;
            }
            case 1 ->{
                int[] positions = {x,y,x+1,y};
                return positions;
            }
            case 2 ->{
                int[] positions = {x,y,x-1,y};
                return positions;
            }
            case 3 ->{
                int[] positions = {x,y,x,y-1};
                return positions;
            }
        }
        return null;
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel armeriaLabel;
    private javax.swing.JPanel bg;
    private javax.swing.JButton button_comprar_componentes;
    private javax.swing.JPanel colorArmeriaPanel;
    private javax.swing.JPanel colorConectorPanel;
    private javax.swing.JPanel colorFuentePanel;
    private javax.swing.JPanel colorMercadoPanel;
    private javax.swing.JPanel colorMinaPanel;
    private javax.swing.JPanel colorTemploPanel;
    private javax.swing.JTextField comandoInput;
    private javax.swing.JLabel conectorLabel;
    private javax.swing.JLabel fuenteLabel;
    private javax.swing.JPanel historialPanel;
    private javax.swing.JComboBox<String> islaCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_player1;
    private javax.swing.JButton jButton_player2;
    private javax.swing.JButton jButton_player3;
    private javax.swing.JLabel jLabel_bomba;
    private javax.swing.JLabel jLabel_canion;
    private javax.swing.JLabel jLabel_canion_barba_roja;
    private javax.swing.JLabel jLabel_multiple;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea_bitacora;
    private javax.swing.JLabel label_acero;
    private javax.swing.JLabel label_dinero;
    private javax.swing.JLabel mercadoLabel;
    private javax.swing.JLabel minaLabel;
    private javax.swing.JPanel panelCuadricula;
    private javax.swing.JPanel panelCuadriculaPlayer;
    private javax.swing.JPanel player2Panel;
    private javax.swing.JPanel player3Panel;
    private javax.swing.JPanel player4Panel;
    private javax.swing.JLabel temploLabel;
    private javax.swing.JPanel textoPanel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JLabel tituloLabel2;
    private javax.swing.JPanel tituloPanel;
    private javax.swing.JPanel tituloPanel2;
    // End of variables declaration//GEN-END:variables

    public JLabel getLabel_acero() {
        return label_acero;
    }

    public JLabel getLabel_dinero() {
        return label_dinero;
    }

    public JLabel getjLabel1() {//Canion
        return jLabel_canion;
    }

    public JLabel getjLabel2() {//Canionmultiple
        return jLabel_multiple;
    }

    public JLabel getjLabel3() {//Bomba
        return jLabel_bomba;
    }

    public JLabel getjLabel4() {//Canion barba roja
        return jLabel_canion_barba_roja;
    }

    public void recibirDisparo(String enviador,String nombre,int x, int y){        
        this.labels[x][y].setText("X");
        this.jTextArea_bitacora.append("Has recibido un disparo de un "+nombre+" de "+ enviador+ " en la posicion ("+x+","+y+")\n");
    }
    public void recibirDisparo(String enviador, String nombre, int[] xys){
        this.labels[xys[0]][xys[1]].setText("X");
        this.labels[xys[2]][xys[3]].setText("X");
        this.jTextArea_bitacora.append("Has recibido una bomba de "+ enviador+ " en las posiciones ("+xys[0]+","+xys[1]+") y ("+xys[2]+","+xys[3]+")\n");
    }
    public void disparoFallado(){
        this.jTextArea_bitacora.append("Y fallo xD\n");
    }
    public void disparoAcertado(String nombreIsla){
        this.jTextArea_bitacora.append("Y se volo "+nombreIsla+" xD\n");
    }
//PROTOTYPES:
    public void invocarKraken(String enviador){
        this.jTextArea_bitacora.append("Has recibido el ataque de kraken de "+enviador+"\n");
    }

    public JTextArea getjTextArea_bitacora() {
        return jTextArea_bitacora;
    }

    public void setjTextArea_bitacora(JTextArea jTextArea_bitacora) {
        this.jTextArea_bitacora = jTextArea_bitacora;
    }

    public JButton getjButton_player1() {
        return jButton_player1;
    }

    public JButton getjButton_player2() {
        return jButton_player2;
    }

    public JButton getjButton_player3() {
        return jButton_player3;
    }
   public void disablePlayerButtons(){
       jButton_player1.setEnabled(false);
       jButton_player2.setEnabled(false);
       jButton_player3.setEnabled(false);
   }

    public JPanel getPanelCuadricula() {
        return panelCuadricula;
    }

    public void setPanelCuadricula(JPanel panelCuadricula) {
        this.panelCuadricula = panelCuadricula;
    }

    public JPanel getPanelCuadriculaPlayer() {
        return panelCuadriculaPlayer;
    }

    public void setPanelCuadriculaPlayer(JPanel panelCuadriculaPlayer) {
        this.panelCuadriculaPlayer = panelCuadriculaPlayer;
    }
    
    public void iniciar_partida(){
        this.jLabel_bomba.setEnabled(true);
        this.jLabel_multiple.setEnabled(true);
        this.jLabel_canion.setEnabled(true);
        this.jLabel_canion_barba_roja.setEnabled(true);
        this.button_comprar_componentes.setEnabled(true);        
    }
    
    public void setCuadricula(Matriz[][] cuadriculaEntrada){
        this.panelCuadriculaPlayer.removeAll();
        for(int i = 0; i<20;i++){
            for(int j = 0; j<20; j++){
                System.out.println(cuadriculaEntrada[i][j].tipo);
                panelCuadriculaPlayer.add(cuadriculaEntrada[i][j].label);
            }
        }
    }
    
}
